name: parts
description: "This is JapanAnimeMaps©️"
publish_to: 'none'

version: 3.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ======================
  # Firebase関連パッケージ
  # ======================
  firebase_core: ^3.13.1
  firebase_auth: ^5.4.5
  firebase_analytics: ^11.4.5
  cloud_firestore: ^5.5.5
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  firebase_remote_config: ^5.3.5
  firebase_in_app_messaging: ^0.8.1+6
  cloud_functions: ^5.5.1
  firebase_database: ^11.3.6

  # ======================
  # Google関連パッケージ
  # ======================
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.1.6
  google_fonts: ^6.2.1
  google_translate: ^0.0.3
  google_mobile_ads: ^5.2.0

  # ======================
  # UI・デザイン関連
  # ======================
  cupertino_icons: ^1.0.6
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  settings_ui: ^2.0.2
  flutter_layout_grid: ^1.0.6
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.1.2
  confetti: ^0.8.0

  # ======================
  # 位置情報・地図関連
  # ======================
  geolocator: ^12.0.0
  map_launcher: ^3.3.1
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0

  # ======================
  # メディア・画像関連
  # ======================
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1
  video_player: ^2.9.1
  youtube_player_iframe: ^5.1.3
  youtube_player_flutter: ^8.1.2
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3

  # ======================
  # ネットワーク・通信関連
  # ======================
  http: ^1.2.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0

  # ======================
  # デバイス機能・センサー関連
  # ======================
  permission_handler: ^11.3.1
  vibration: ^1.9.0
  sensors_plus: ^6.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # ======================
  # ストレージ・データ関連
  # ======================
  shared_preferences: ^2.3.3
  path_provider: ^2.1.3

  # ======================
  # 国際化・ローカライゼーション
  # ======================
  intl: ^0.19.0
  translator: ^1.0.0

  # ======================
  # 通知・メッセージング関連
  # ======================
  flutter_local_notifications: ^17.2.2
  flutter_email_sender: ^6.0.3
  fluttertoast: ^8.2.8

  # ======================
  # 認証・セキュリティ関連
  # ======================
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.2

  # ======================
  # アプリ情報・設定関連
  # ======================
  package_info_plus: ^8.0.1
  flutter_launcher_icons: ^0.13.1

  # ======================
  # 共有・ソーシャル関連
  # ======================
  share: ^2.0.4
  share_plus: ^10.0.0

  # ======================
  # チュートリアル・ガイド関連
  # ======================
  showcaseview: ^4.0.1

  # ======================
  # 課金・決済関連
  # ======================
  in_app_purchase: ^3.2.0
  purchases_flutter: ^8.2.0
  flutter_stripe: ^10.1.1

  # ======================
  # バックグラウンド・ワーカー関連
  # ======================
  workmanager: ^0.5.2
  flutter_background_service: ^5.1.0

  # ======================
  # レビュー・フィードバック関連
  # ======================
  in_app_review: ^2.0.10

  # ======================
  # プライバシー・トラッキング関連
  # ======================
  app_tracking_transparency: ^2.0.6

  # ======================
  # その他のユーティリティ
  # ======================
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/apps_icon.png"
  min_sdk_android: 21

# ここに dependency_overrides を移動（flutterセクションの外）
dependency_overrides:
  stripe_platform_interface: ^10.0.0
  stripe_android: ^10.0.0
  stripe_ios: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/