// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFBNB_lBR1gYsDN73w9ErjcAoFO1TPo4',
    appId: '1:223327218351:web:5d81ef28af220bc7ca425a',
    messagingSenderId: '223327218351',
    projectId: 'anime-97d2d',
    authDomain: 'anime-97d2d.firebaseapp.com',
    storageBucket: 'anime-97d2d.appspot.com',
    measurementId: 'G-1SBT7HQVQL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HES7HOQTK-t_6JGi-cWfIZbqDiOad7U',
    appId: '1:223327218351:ios:63dec507edebae23ca425a',
    messagingSenderId: '223327218351',
    projectId: 'anime-97d2d',
    storageBucket: 'anime-97d2d.appspot.com',
    iosBundleId: 'com.example.parts0705',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HES7HOQTK-t_6JGi-cWfIZbqDiOad7U',
    appId: '1:223327218351:ios:1a9d70d713e61b0cca425a',
    messagingSenderId: '223327218351',
    projectId: 'anime-97d2d',
    storageBucket: 'anime-97d2d.appspot.com',
    iosBundleId: 'com.example.parts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRFBNB_lBR1gYsDN73w9ErjcAoFO1TPo4',
    appId: '1:223327218351:web:fd61b124a38d6924ca425a',
    messagingSenderId: '223327218351',
    projectId: 'anime-97d2d',
    authDomain: 'anime-97d2d.firebaseapp.com',
    storageBucket: 'anime-97d2d.appspot.com',
    measurementId: 'G-FW3S0SNV5V',
  );
}
